name       : tilix
version    : 1.8.1
release    : 13
source     :
    - https://github.com/gnunn1/tilix/archive/1.8.1.tar.gz : 9ead61aee6112797751f21eddea57e5f817aa39d44ee72a6a377f5f5c1d0ea78
license    :
    - GPL-3.0-or-later
    - MPL-2.0
component  : system.utils
summary    : A tiling terminal emulator for Linux using GTK+ 3
description: |
    Tilix is an advanced GTK3 tiling terminal emulator that follows the Gnome Human Interface Guidelines.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtkd-3)
    - ldc
    - po4a
rundeps    :
    - libvte
setup      : |
    %autogen
build      : |
    %make DCFLAGS='-O -inline -release -version=StdLoggerDisableTrace'
install    : |
    %make_install
