name       : tilix
version    : 1.8.9
release    : 18
source     :
    - https://github.com/gnunn1/tilix/archive/1.8.9.tar.gz : 0cee8a42a0537bb235005a63030af0839eb8351e8a2ca287de153d1dcc561332
license    :
    - GPL-3.0-or-later
    - MPL-2.0
component  : system.utils
summary    : A tiling terminal emulator for Linux using GTK+ 3
description: |
    Tilix is an advanced GTK3 tiling terminal emulator that follows the Gnome Human Interface Guidelines.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtkd-3)
    - binutils-gold
    - ldc
    - po4a
rundeps    :
    - libvte
setup      : |
    %autogen
build      : |
    %make DCFLAGS='-O -inline -release -version=StdLoggerDisableTrace'
install    : |
    %make_install
