name       : tilix
version    : 1.9.5
release    : 44
source     :
    - git|https://github.com/gnunn1/tilix.git : 5bbd0fc6075dd8d480e943671b8d99ecb0e9c2fe
license    :
    - GPL-3.0-or-later
    - MPL-2.0
component  : system.utils
summary    : A tiling terminal emulator for Linux using GTK+ 3
description: |
    Tilix is an advanced GTK3 tiling terminal emulator that follows the Gnome Human Interface Guidelines.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtkd-3)
    - pkgconfig(libsecret-1)
    - pkgconfig(libunwind)
    - desktop-file-utils
    - ldc
    - po4a
rundeps    :
    - libvte
setup      : |
    %patch -p1 < $pkgfiles/0001-Remove-appstreamcli-because-we-don-t-have-it-in-Solu.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
