name       : tilix
version    : 1.9.3
release    : 21
source     :
    - https://github.com/gnunn1/tilix/archive/1.9.3.tar.gz : f1b4dbbd60f4b9a91e0ab0954e3e6b8ebe5442d5fbb760a554a733903e44a1de
license    :
    - GPL-3.0-or-later
    - MPL-2.0
component  : system.utils
summary    : A tiling terminal emulator for Linux using GTK+ 3
description: |
    Tilix is an advanced GTK3 tiling terminal emulator that follows the Gnome Human Interface Guidelines.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtkd-3)
    - binutils-gold
    - ldc
    - po4a
rundeps    :
    - libvte
setup      : |
    %autogen
build      : |
    %make DCFLAGS='-O -inline -release -version=StdLoggerDisableTrace'
install    : |
    %make_install
