name       : tilix
version    : 1.7.9
release    : 11
source     :
    - https://github.com/gnunn1/tilix/archive/1.7.9.tar.gz : 2a9a183daf1edd5a04925647d2624b61cad72ef04aaf152b0c71c94360ccfb24
license    : MPL-2.0
component  : system.utils
summary    : A tiling terminal emulator for Linux using GTK+ 3
description: |
    Tilix is an advanced GTK3 tiling terminal emulator that follows the Gnome Human Interface Guidelines
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtkd-3)
    - ldc
    - po4a
rundeps    :
    - libvte
setup      : |
    %autogen
    %configure
build      : |
    %make DCFLAGS='-O -inline -release -version=StdLoggerDisableTrace'
install    : |
    %make_install
