name       : tilix
version    : 1.8.7
release    : 17
source     :
    - https://github.com/gnunn1/tilix/archive/1.8.7.tar.gz : ad09434a7f2b62b0016e31f8a298c7a26ecda159835cf80d0d2af3173e098d0e
license    :
    - GPL-3.0-or-later
    - MPL-2.0
component  : system.utils
summary    : A tiling terminal emulator for Linux using GTK+ 3
description: |
    Tilix is an advanced GTK3 tiling terminal emulator that follows the Gnome Human Interface Guidelines.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtkd-3)
    - binutils-gold
    - ldc
    - po4a
rundeps    :
    - libvte
setup      : |
    %autogen
build      : |
    %make DCFLAGS='-O -inline -release -version=StdLoggerDisableTrace'
install    : |
    %make_install
