name       : tilix
version    : 1.7.7
release    : 9
source     :
    - https://github.com/gnunn1/tilix/archive/1.7.7.tar.gz : 9c8ba7734c61fee7efcd3c75548c996216383092e4d33472aeaa457ddfdb3828
license    : MPL-2.0
component  : system.utils
summary    : A tiling terminal emulator for Linux using GTK+ 3
description: |
    Tilix is an advanced GTK3 tiling terminal emulator that follows the Gnome Human Interface Guidelines
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtkd-3)
    - ldc
    - po4a
setup      : |
    %autogen
    %configure
build      : |
    %make DCFLAGS='-O -inline -release -version=StdLoggerDisableTrace'
install    : |
    %make_install
