name       : tilix 
version    : 1.7.1
release    : 1
source     :
    - https://github.com/gnunn1/tilix/archive/1.7.1.tar.gz : 1b807ba47d90c849e1712da7213daf46b63bb36c0b9bd6eaec9bc4c5f84465de
license    : MPL-2.0
component  : system.utils 
summary    : A tiling terminal emulator for Linux using GTK+ 3  
description: |
    Tilix is an advanced GTK3 tiling terminal emulator that follows the Gnome Human Interface Guidelines.
networking: yes
builddeps  :
    - pkgconfig(gtk+-3.0)
    - desktop-file-utils
    - dmd
    - dub
    - xdg-utils
build    : |
    dub upgrade
    dub build --build=release
install  : |
    ./install.sh $installdir/usr
