name       : tilix
version    : 1.7.3
release    : 3
source     :
    - https://github.com/gnunn1/tilix/archive/1.7.3.tar.gz : c05cac4073267e576671f69613f644c4b52769253edd473a48f406b7f10d954c
license    : MPL-2.0
component  : system.utils
summary    : A tiling terminal emulator for Linux using GTK+ 3
description: |
    Tilix is an advanced GTK3 tiling terminal emulator that follows the Gnome Human Interface Guidelines.
networking : yes
builddeps  :
    - pkgconfig(gtk+-3.0)
    - desktop-file-utils
    - dmd
    - dub
    - xdg-utils
build      : |
    dub upgrade
    dub build --build=release
install    : |
    ./install.sh $installdir/usr
    # Naughty.
    rm -v $installdir/usr/share/glib-2.0/schemas/gschemas.compiled
