name       : tilix
version    : 1.7.5
release    : 4
source     :
    - https://github.com/gnunn1/tilix/archive/1.7.5.tar.gz : 324c565e71ae5f975d5488241915c1e12eb27695a1d4b896443fb7ef02dd39c0
license    : MPL-2.0
component  : system.utils
summary    : A tiling terminal emulator for Linux using GTK+ 3
description: |
    Tilix is an advanced GTK3 tiling terminal emulator that follows the Gnome Human Interface Guidelines.
networking : yes
builddeps  :
    - pkgconfig(gtk+-3.0)
    - desktop-file-utils
    - dmd
    - dub
    - xdg-utils
build      : |
    dub upgrade
    dub build --build=release
install    : |
    ./install.sh $installdir/usr
    # Naughty.
    rm -v $installdir/usr/share/glib-2.0/schemas/gschemas.compiled
