name       : tilix
version    : 1.8.5
release    : 15
source     :
    - https://github.com/gnunn1/tilix/archive/1.8.5.tar.gz : b4fd4624a39b19c612199ffb56b5d617afbbab8995a4c0da66ef80ed193c616f
license    :
    - GPL-3.0-or-later
    - MPL-2.0
component  : system.utils
summary    : A tiling terminal emulator for Linux using GTK+ 3
description: |
    Tilix is an advanced GTK3 tiling terminal emulator that follows the Gnome Human Interface Guidelines.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtkd-3)
    - ldc
    - po4a
rundeps    :
    - libvte
setup      : |
    %autogen
build      : |
    %make DCFLAGS='-O -inline -release -version=StdLoggerDisableTrace'
install    : |
    %make_install
